---
title: "Chapter_8"
output: github_document
---

Code for the Chapter 8 of the [Modern Dive book](https://moderndive.com/8-confidence-intervals.html).

```{r load-packages}
library(tidyverse)
library(moderndive)
library(infer)
library(ggthemes)
```

Set the palette and the running theme for ggplot2.

```{r set-theme-palette}
theme_set(theme_bw())
theme_update(axis.text.x = element_text(
angle = -45,
hjust = 0,
vjust = 0.5
))
```

## 8,.1

### 8.1.1

```{r}
glimpse(pennies_sample)
```

```{r}
pennies_sample %>%
  ggplot(aes(x = year)) +
  geom_histogram(binwidth = 10,
                 color = "white")
```

```{r}
x_bar <- pennies_sample %>%
  summarise(mean_year = mean(year))

x_bar
```

### 8.1.2

```{r}
pennies_resample <- tibble(
  year = c(1976, 1962, 1976, 1983, 2017, 2015, 2015, 1962, 2016, 1976, 
           2006, 1997, 1988, 2015, 2015, 1988, 2016, 1978, 1979, 1997, 
           1974, 2013, 1978, 2015, 2008, 1982, 1986, 1979, 1981, 2004, 
           2000, 1995, 1999, 2006, 1979, 2015, 1979, 1998, 1981, 2015, 
           2000, 1999, 1988, 2017, 1992, 1997, 1990, 1988, 2006, 2000)
)
```

```{r}
pennies_resample %>%
  ggplot(aes(x = year)) +
  geom_histogram(binwidth = 10,
                 color = "white")
```

```{r}
pennies_resample %>%
  summarise(mean_year = mean(year))
```

```{r}
glimpse(pennies_resamples)
```

```{r}
resampled_means <- pennies_resamples %>%
  group_by(name) %>%
  summarise(mean_year = mean(year))

resampled_means
```

```{r}
resampled_means %>%
  ggplot(aes(x = mean_year)) +
  geom_histogram(binwidth = 1,
                 boundary = 1990,
                 color = "white") +
  labs(x = "Resampled Mean Year")
```

## 8.2

### 8.1

```{r}
set.seed(42)

virtual_resample <- pennies_sample %>%
  rep_sample_n(size = 50, replace = TRUE)

virtual_resample
```

```{r}
virtual_resample %>%
  summarise(resample_mean = mean(year))
```

```{r}
virtual_resamples <- pennies_sample %>%
  rep_sample_n(size = 50, 
               replace = TRUE,
               reps = 35)

virtual_resamples
```

```{r}
virtual_resampled_means <- virtual_resamples %>%
  group_by(replicate) %>%
  summarise(mean_year = mean(year))

virtual_resampled_means
```

```{r}
virtual_resampled_means %>%
  ggplot(aes(x = mean_year)) +
  geom_histogram(binwidth = 1,
                 boundary = 1990,
                 color = "white") +
  labs(x = "Virtual Resampled Mean Year")
```

```{r}
virtual_resampled_means <- pennies_sample %>%
  rep_sample_n(size = 50, 
               replace = TRUE,
               reps = 1000) %>%
  group_by(replicate) %>%
  summarise(mean_year = mean(year))

virtual_resampled_means
```

```{r}
virtual_resampled_means %>%
  ggplot(aes(x = mean_year)) +
  geom_histogram(binwidth = 1,
                 boundary = 1990,
                 color = "white") +
  labs(x = "Virtual Resampled Mean Year")
```

## 8.3

### 8.3.1

```{r}
CI95_q <- quantile(virtual_resampled_means$mean_year,c(0.025, 0.975))

CI95_q
```

```{r}
virtual_resampled_means %>%
  ggplot(aes(x = mean_year)) +
  geom_histogram(binwidth = 1,
                 boundary = 1990,
                 color = "white") +
  geom_vline(xintercept = CI95_q,
             linetype = "longdash",
             color = "grey70") +
  
  labs(x = "Virtual Resampled Mean Year")
```

```{r}
CI95_n <- virtual_resampled_means %>%
  summarise(means_of_means = mean(mean_year),
            sd_of_mean = sd(mean_year)) %>%
  mutate(CI95_low = means_of_means - 1.96 * sd_of_mean,
         CI95_high = means_of_means + 1.96 * sd_of_mean) %>%
  select(CI95_low, CI95_high) %>%
  pivot_longer(cols = c(CI95_low, CI95_high)) %>%
  pull(value)

CI95_n
```

```{r}
virtual_resampled_means %>%
  ggplot(aes(x = mean_year)) +
  geom_histogram(binwidth = 1,
                 boundary = 1990,
                 color = "white") +
  geom_vline(xintercept = CI95_q,
             linetype = "longdash",
             color = "grey70") +
  geom_vline(xintercept = CI95_n,
             linetype = "longdash",
             color = "red") +
  
  labs(x = "Virtual Resampled Mean Year")
```

## 8.4

### 8.4.2

```{r}
pennies_sample %>%
  summarize(stat = mean(year))
```

```{r}
pennies_sample %>%
  specify(response = year) %>%
  calculate(stat = "mean")
```

```{r}
pennies_sample %>%
  specify(response = year)
```

```{r}
pennies_sample %>%
  specify(formula = year ~ NULL)
```

```{r}
pennies_sample %>%
  specify(formula = year ~ NULL) %>%
  generate(reps = 1000, type = "bootstrap")
```

```{r}
bootstrap_distr <- pennies_sample %>%
  specify(formula = year ~ NULL) %>%
  generate(reps = 1000) %>%
  calculate(stat = "mean")

bootstrap_distr
```

```{r}
visualize(bootstrap_distr)
```

### 8.4.3

```{r}
percentile_ci <- bootstrap_distr %>%
  get_confidence_interval(level = 0.95, type = "percentile")

percentile_ci
```

```{r}
visualize(bootstrap_distr) +
  shade_confidence_interval(endpoints = percentile_ci,
                            color = "navyblue",
                            fill = "gray70")
```

### 8.4.4

```{r}
standard_error_ci <- bootstrap_distr %>%
  get_confidence_interval(type = "se", point_estimate = x_bar)

standard_error_ci
```

```{r}
visualize(bootstrap_distr) +
  shade_confidence_interval(endpoints = standard_error_ci,
                            color = "red",
                            fill = "gray70")
```

## 8.5

```{r}
bowl %>%
  summarize(p_red = mean(color == "red"))
```

```{r}
bowl_sample_1
```

```{r}
p_hat <- bowl_sample_1 %>% 
  summarise(prop = mean(color == "red")) %>%
  pull(prop)

p_hat
```

```{r}
bowl_sample_1 %>%
  specify(response = color, success = "red")
```

```{r}
bowl_sample_1 %>%
  specify(response = color, success = "red") %>%
  generate(reps = 1000, type = "bootstrap")
```

```{r}
sample_1_bootstrap <- bowl_sample_1 %>%
  specify(response = color, success = "red") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "prop")
```

```{r}
percentile_ci_1 <- sample_1_bootstrap %>%
  get_ci(level = 0.95, type = "percentile")

percentile_ci_1
```

```{r}
sample_1_bootstrap %>%
  visualize(bins = 15) +
  shade_ci(endpoints = percentile_ci_1,
           color = "navyblue",
           fill = "grey70") +
  geom_vline(xintercept = p_hat,
             linetype = "longdash",
             color = "darkred")
```

```{r}
bowl_sample_2 <- bowl %>%
  rep_sample_n(size = 50)

bowl_sample_2
```

```{r}
sample_2_bootstrap <- bowl_sample_2 %>%
  specify(response = color, success = "red") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "prop")

sample_2_bootstrap
```

```{r}
percentile_ci_2 <- sample_2_bootstrap %>%
  get_ci(level = 0.95, type = "percentile")

percentile_ci_2
```

## 8.6

```{r}
mythbusters_yawn
```

```{r}
mythbusters_yawn %>%
  count(group, yawn)
```

```{r}
mythbusters_yawn %>%
  specify(formula = yawn ~ group, success = "yes")
```

```{r}
mythbusters_yawn %>%
  specify(formula = yawn ~ group, success = "yes") %>%
  generate(reps = 1000, type = "bootstrap")
```

```{r}
mythbusters_yawn %>%
  specify(formula = yawn ~ group, success = "yes") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "diff in props")
```

```{r}
bootstrap_distr_yawning <- mythbusters_yawn %>%
  specify(formula = yawn ~ group, success = "yes") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "diff in props", order = c("seed", "control"))

bootstrap_distr_yawning
```

```{r}
visualize(bootstrap_distr_yawning) +
  geom_vline(xintercept = 0)
```

```{r}
myth_ci_q <- bootstrap_distr_yawning %>%
  get_confidence_interval(type = "percentile")

myth_ci_q
```

```{r}
obs_diff_in_props <- mythbusters_yawn %>%
  specify(formula = yawn ~ group, success = "yes") %>%
  calculate(stat = "diff in props", order = c("seed", "control"))

obs_diff_in_props
```

```{r}
myth_ci_se <- bootstrap_distr_yawning %>%
  get_ci(type = "se", point_estimate = obs_diff_in_props)

myth_ci_se
```

```{r}
visualize(bootstrap_distr_yawning) +
  shade_ci(endpoints = myth_ci_q,
           color = "darkblue",
           fill = NULL) +
  shade_ci(endpoints = myth_ci_se,
           color = "darkred",
           fill = NULL)
```

Document the information about the analysis session

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```
