---
title: "Chapter_7"
output: github_document
---

Code for the Chapter 7 of the [Modern Dive book](https://moderndive.com/7-regression.html#regression).

```{r load-packages}
library(tidyverse)
library(glue)
library(moderndive)
library(ggthemes)
```

Set the palette and the running theme for ggplot2.

```{r set-theme-palette}
theme_set(theme_bw())
theme_update(axis.text.x = element_text(
angle = -45,
hjust = 0,
vjust = 0.5
))
```


### 7.1.3
```{r}
tactile_prop_red
```
```{r}
ggplot(tactile_prop_red, aes(x = prop_red)) +
  geom_histogram(binwidth = 0.05,
                 boundary = 0.4,
                 color = "white") +
  labs(x = "Proportion of 50 balls that were red",
       title = "Distribution of 33 proportions red")
```
```{r}
glimpse(bowl)
```

```{r}
plot_red_prop <- function(sample_size) {
  bowl %>%
    rep_sample_n(sample_size, 1000, replace = T) %>%
    group_by(replicate) %>%
    summarise(prop_red = mean(color == "red")) %>%
    ggplot(aes(x = prop_red)) +
    geom_histogram(binwidth = 0.05,
                   boundary = 0.4,
                   color = "white") +
    scale_x_continuous(breaks = seq(0.1, 0.9, 0.1)) +
    coord_cartesian(xlim = c(0.1, 0.9)) +
    labs(x = glue("proportion of {sample_size} balls that were red"),
         y = "Count",
         title = glue("{sample_size}"))
}
```

```{r}
set.seed(1942)

sample_sizes <- c(25, 50, 100)

  map(sample_sizes, ~ plot_red_prop(.x))
```

```{r}
calc_red_prop_sd <- function(sample_size) {
  bowl %>%
    rep_sample_n(sample_size, 1000, replace = T) %>%
    group_by(replicate) %>%
    summarise(prop_red = mean(color == "red")) %>%
    ungroup() %>%
    summarise(sd = sd(prop_red))
}
```

```{r}
map_df(sample_sizes, ~calc_red_prop_sd(.x))
```
## 7.3

Document the information about the analysis session

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```
