---
title: "Chapter_5"
output: github_document
---

Code for the Chapter 5 of the [Modern Dive book](https://moderndive.com/5-regression.html#regression).

```{r load-packages}
library(tidyverse)
library(moderndive)
library(skimr)
library(gapminder)
```
Set the palette and the running theme for ggplot2.
```{r set-theme-palette}
theme_set(theme_bw())
theme_update(axis.text.x = element_text(
angle = -45,
hjust = 0,
vjust = 0.5
))
```

## 5.1

```{r}
glimpse(evals)
```
### 5.1

```{r}
evals_ch5 <- evals %>%
  select(ID, score:bty_avg)

glimpse(evals_ch5)
```

```{r}
set.seed(42)

evals_ch5 %>%
  sample_n(size = 5)
```

```{r}
evals_ch5 %>%
  summarise(across(c(bty_avg, score),
                   list(mean = mean, median = median)))
```

```{r}
evals_ch5 %>%
  select(bty_avg, score) %>%
  skim()
```

```{r}
evals_ch5 %>%
  summarise(correlation = cor(bty_avg, score))
```

```{r}
evals_ch5 %>%
  ggplot(aes(x = bty_avg, y = score)) +
  geom_point() +
  labs(x = "Average Beauty",
       y = "Course Score",
       title = "Relationship between beauty and score")
```

```{r}
evals_ch5 %>%
  ggplot(aes(x = bty_avg, y = score)) +
  geom_jitter() +
  labs(x = "Average Beauty",
       y = "Course Score",
       title = "Relationship between beauty and score with jitter")
```

```{r}
evals_ch5 %>%
  ggplot(aes(x = bty_avg, y = score)) +
  geom_point() +
  labs(x = "Average Beauty",
       y = "Course Score",
       title = "Relationship between beauty and score") +
  geom_smooth(method = "lm",
              se = FALSE)
```

### LC5.1

```{r}
evals_ch5 %>%
  select(score, age) %>%
  skim()
```


```{r}
evals_ch5 %>%
  get_correlation(score ~ age)
```
```{r}
evals_ch5 %>%
  ggplot(aes(x = age, y = score)) +
  geom_point() +
  labs(x = "Age (Years)",
       y = "Course Score",
       title = "Relationship between age and score") +
  geom_smooth(method = "lm",
              se = FALSE)
```
### 5.1.2

```{r}
score_model_1 <- lm(score ~ bty_avg, data = evals_ch5)
get_regression_table(score_model_1)
```
### LC5.2

```{r}
score_model_2 <- lm(score ~ age, data = evals_ch5)
get_regression_table(score_model_2)
```
```{r}
score_model_3 <- lm(score ~ bty_avg + age , data = evals_ch5)
get_regression_table(score_model_3)
```

### 5.1.3

```{r}
regression_points_1 <- get_regression_points(score_model_1)

regression_points_1
```

### LC5.3

```{r}
regression_points_2 <- get_regression_points(score_model_2)

regression_points_2
```

## 5.2

### 5.2.1
```{r}
library(gapminder)

gapminder2007 <- gapminder %>%
  filter(year == 2007) %>%
  select(country, lifeExp, continent, gdpPercap)

glimpse(gapminder2007)
```

```{r}
set.seed(2701)

gapminder2007 %>% sample_n(size = 5)
```

```{r}
gapminder2007 %>%
  select(lifeExp, continent) %>%
  skim()
```
```{r}
gapminder2007 %>%
  ggplot(aes(x = lifeExp)) +
  geom_histogram(binwidth = 5, 
                 color = "white") +
  labs(x = "Life Expectancy",
       y = "Number of Contries",
       title = "Histogram of worldwide life expectancies")
```
```{r}
gapminder2007 %>%
  ggplot(aes(x = lifeExp)) +
  geom_histogram(binwidth = 5, 
                 color = "white") +
  facet_wrap(vars(continent), nrow = 2) +
  labs(x = "Life Expectancy",
       y = "Number of Contries",
       title = "Histogram of per continent life expectancies")
```
```{r}
gapminder2007 %>%
  ggplot(aes(x = continent, y = lifeExp)) +
  geom_boxplot() +
  labs(x = "Continent",
       y = "Life Expectancy",
       title = "Boxplot of per continent life expectancies")
```
```{r}
gapminder2007 %>%
  group_by(continent) %>%
  summarize(across(lifeExp, list(mean = mean, median = median)))
```
```{r}
gapminder2007 %>%
  group_by(continent) %>%
  summarise(mean = mean(lifeExp)) %>%
  mutate(africa_diff = mean - 54.8)
```

### LC5.4

```{r}
gapminder2007 %>%
  ggplot(aes(x = gdpPercap)) +
  geom_histogram(binwidth = 2500,
                 color = "white") +
  facet_wrap(vars(continent), nrow = 2) +
  labs(x = "2007 GDP per Capita in USD",
       y = "Number of Contries",
       title = "Histogram of per continent 2007 GDP")
  
```

```{r}
gapminder2007 %>%
  ggplot(aes(x = continent, y = gdpPercap)) +
  geom_boxplot() +
  labs(x = "Continent",
       y = "2007 GDP per Capita in USD",
       title = "Boxplot of per continent 2007 GDP")
```

Document the information about the analysis session

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```
