---
title: "Chapter_9"
output: github_document
---

Code for the Chapter 9 of the [Modern Dive book](https://moderndive.com/9-hypothesis-testing.html).

```{r load-packages}
library(tidyverse)
library(infer)
library(moderndive)
library(nycflights13)
library(ggplot2movies)
library(ggthemes)
```

Set the palette and the running theme for ggplot2.

```{r set-theme-palette}
theme_set(theme_bw())
theme_update(axis.text.x = element_text(
angle = -45,
hjust = 0,
vjust = 0.5
))
```

## 9.1
### 9.1.1

```{r}
set.seed(42)

promotions %>%
  sample_n(size = 6) %>%
  arrange(id)
```

```{r}
promotions %>%
  ggplot(aes(x = gender,
             fill = decision)) +
  geom_bar() +
  scale_fill_tableau() +
  labs(x = "Gender of name on rèsumè") 
```

```{r}
promotions %>%
  count(gender, decision)
```

```{r}
promotions_shuffled %>%
  ggplot(aes(x = gender,
             fill = decision)) +
  geom_bar() +
  scale_fill_tableau() +
  labs(x = "Gender of name on rèsumè")
```

```{r}
promotions_shuffled %>%
  count(gender, decision)
```

## 9.3
### 9.3.1
```{r}
promotions %>%
  specify(formula = decision ~ gender,
          success = "promoted")
```

```{r}
promotions %>%
  specify(formula = decision ~ gender,
          success = "promoted") %>%
  hypothesize(null = "independence")
```

```{r}
promotions_generate <- promotions %>%
  specify(formula = decision ~ gender,
          success = "promoted") %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, 
           type = "permute")

promotions_generate
```

```{r}
null_distribution <- promotions %>%
  specify(formula = decision ~ gender,
          success = "promoted") %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, 
           type = "permute") %>%
  calculate(stat = "diff in props",
            order = c("male", "female"))

null_distribution
```


```{r}
obs_diff_prop <- promotions %>%
  specify(formula = decision ~ gender,
          success = "promoted") %>%
  calculate(stat = "diff in props",
            order = c("male", "female"))

obs_diff_prop
```

```{r}
visualize(null_distribution, bins = 10)
```

```{r}
visualize(null_distribution, bins = 10) +
  shade_p_value(obs_stat = obs_diff_prop, direction = "right")
```

```{r}
null_distribution %>%
  get_p_value(obs_stat = obs_diff_prop, 
              direction = "right")
```
### 9.3.2 

```{r}
bootstrap_distribution <- promotions %>%
  specify(formula = decision ~ gender,
          success = "promoted") %>%
  # Remove hypothesize()
  #hypothesize(null = "independence") %>%
  # Change type from "permute" to "bootstrap"
  generate(reps = 1000, 
           type = "bootstrap") %>%
  calculate(stat = "diff in props",
            order = c("male", "female"))

bootstrap_distribution
```

```{r}
percentile_ci <- bootstrap_distribution %>%
  get_ci(type = "percentile")

percentile_ci
```
```{r}
visualize(bootstrap_distribution) +
  shade_ci(endpoints = percentile_ci,
           color = "darkblue",
           fill = "grey70")
```

```{r}
se_ci <- bootstrap_distribution %>%
  get_ci(type = "se", point_estimate = obs_diff_prop)

se_ci
```

```{r}
visualize(bootstrap_distribution) +
  shade_ci(endpoints = se_ci,
           color = "darkred",
           fill = "grey70")
```

## 9.5
### 9.5.1

```{r}
glimpse(movies)
```

```{r}
glimpse(movies_sample)
```
```{r}
movies_sample %>%
  ggplot(aes(x = genre, y = rating)) +
  geom_boxplot() +
  geom_jitter(shape = 21) +
  labs(x = "Genre",
       y = "IMDB Rating")
```

```{r}
movies_sample %>%
  group_by(genre) %>%
  summarize(n = n(),
            rating_mean = mean(rating),
            rating_sd = sd(rating))
```

```{r}
movies_sample %>%
  specify(formula = rating ~ genre)
```

```{r}
movies_sample %>%
  specify(formula = rating ~ genre) %>%
  hypothesize(null = "independence")
```
```{r}
movies_sample %>%
  specify(formula = rating ~ genre) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute")
```
```{r}
null_distr_movies <- movies_sample %>%
  specify(formula = rating ~ genre) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>%
  calculate(stat = "diff in means", order = c("Action", "Romance"))

null_distr_movies
```
```{r}
obs_diff_means <- movies_sample %>%
  specify(formula = rating ~ genre) %>%
  calculate(stat = "diff in means", order = c("Action", "Romance"))

obs_diff_means
```

```{r}
visualize(null_distr_movies, bins = 10) +
  shade_p_value(obs_stat = obs_diff_means, direction = "both")
```

```{r}
null_distr_movies %>%
  get_p_value(obs_stat = obs_diff_means, direction = "both")
```

Document the information about the analysis session

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```
