---
title: "Chapter_6"
output: github_document
---

Code for the Chapter 6 of the [Modern Dive book](https://moderndive.com/6-multiple-regression.html).

```{r load-packages}
library(tidyverse)
library(moderndive)
library(skimr)
library(ISLR)
library(ggthemes)
```

Set the palette and the running theme for ggplot2.

```{r set-theme-palette}
theme_set(theme_bw())
theme_update(axis.text.x = element_text(
angle = -45,
hjust = 0,
vjust = 0.5
))
```

## 6.1

```{r}
evals_ch6 <- evals %>%
  select(ID, score, age, gender)

glimpse(evals_ch6)
```

```{r}
evals_ch6 %>%
  summarise(across(c(age, score),
                   list(mean = mean, median = median)))
```
```{r}
evals_ch6 %>%
  skim()
```
```{r}
evals_ch6 %>%
  get_correlation(score ~ age)
```
```{r}
evals_ch6 %>%
  ggplot(aes(x = age, 
             y = score,
             color = gender)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_tableau(name = "Gender") +
  labs(x = "Age",
       y = "Teaching Score")
```
```{r}
score_model_interaction <- lm(score ~ age * gender, data = evals_ch6)

get_regression_table(score_model_interaction)
```

### 6.1.3
```{r}
evals_ch6 %>%
  ggplot(aes(x = age, 
             y = score,
             color = gender)) +
  geom_point() +
  geom_parallel_slopes(se = FALSE) +
  scale_color_tableau(name = "Gender") +
  labs(x = "Age",
       y = "Teaching Score")
```
```{r}
score_model_parallel_slopes <- lm(score ~ age + gender, data = evals_ch6)
get_regression_table(score_model_parallel_slopes)
```
```{r}
regression_points_interaction <- get_regression_points(score_model_interaction)
regression_points_interaction
```
### LC6.1
```{r}
regression_points_parallel <- get_regression_points(score_model_parallel_slopes)
regression_points_parallel
```
### 6.2
```{r}
library(ISLR)

credit_ch6 <- Credit %>% 
  as_tibble() %>%
  select(ID, 
         debt = Balance,
         credit_limit = Limit,
         income = Income,
         credit_rating = Rating,
         age = Age)

glimpse(credit_ch6)
```
```{r}
credit_ch6 %>%
  select(debt, credit_limit, income) %>%
  skim()
```
```{r}
credit_ch6 %>%
  select(debt, credit_limit, income) %>%
  cor()
```
```{r}
credit_ch6 %>%
  ggplot(aes(x = credit_limit,
             y = debt)) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE) +
  labs(x = "Credit Limit ($1000)",
       y = "Credit Card Debt ($1000)",
       title = "Debt and Credit Limit")

credit_ch6 %>%
  ggplot(aes(x = income,
             y = debt)) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE) +
  labs(x = "Income ($1000)",
       y = "Credit Card Debt ($1000)",
       title = "Debt and Income")
```
### LC6.2
```{r}
credit_ch6 %>%
  select(debt, age, credit_rating) %>%
  skim()
```
```{r}
credit_ch6 %>%
  select(debt, credit_rating, age) %>%
  cor()
```

```{r}
credit_ch6 %>%
  ggplot(aes(x = credit_rating,
             y = debt)) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE) +
  labs(x = "Credit Rating",
       y = "Credit Card Debt ($1000)",
       title = "Debt and Credit Rating")

credit_ch6 %>%
  ggplot(aes(x = age,
             y = debt)) +
  geom_point() +
  geom_smooth(method = "lm",
              se = FALSE) +
  labs(x = "Age",
       y = "Credit Card Debt ($1000)",
       title = "Debt and Age")
```

### 6.2.2

```{r}
debt_model <- lm(debt ~ credit_limit + income, data = credit_ch6)
get_regression_table(debt_model)
```

### LC6.3
```{r}
debt_model_lc63 <- lm(debt ~ credit_rating + age, data = credit_ch6)
get_regression_table(debt_model_lc63)
```
### 6.2.3

```{r}
get_regression_points(debt_model)
```
## 6.3
### 6.3.1

```{r}
glimpse(MA_schools)
```
```{r}
MA_schools %>%
  select(-school_name) %>%
  skim()
```
```{r}
ggplot(MA_schools,
       aes(x = perc_disadvan,
           y = average_sat_math,
           color = size)) +
  geom_point(alpha = 0.25) +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_tableau() +
  labs(x = "Percentage Economically Disadvantaged",
       y = "Average SAT in Mathematics",
       color = "School Size")
```
```{r}
ggplot(MA_schools,
       aes(x = perc_disadvan,
           y = average_sat_math,
           color = size)) +
  geom_point(alpha = 0.25) +
  geom_parallel_slopes(se = FALSE) +
  scale_color_tableau() +
  labs(x = "Percentage Economically Disadvantaged",
       y = "Average SAT in Mathematics",
       color = "School Size")
```

```{r}
model_2_interaction <- lm(average_sat_math ~ perc_disadvan * size, 
                          data = MA_schools)

get_regression_table(model_2_interaction)
```
```{r}
model_2_parallel_slopes <- lm(average_sat_math ~ perc_disadvan + size, 
                          data = MA_schools)

get_regression_table(model_2_parallel_slopes)
```

### 6.3.2
```{r}
get_regression_points(model_2_interaction)
```
```{r}
get_regression_points(model_2_interaction) %>%
  summarise(across(c(average_sat_math, average_sat_math_hat, residual),
            list(var = var)))
```
```{r}
get_regression_summaries(model_2_interaction)
```
### 6.3.3

Document the information about the analysis session

```{r sessionInfo, include=TRUE, echo=TRUE, results='markup'}
sessionInfo()
```
